import { UserRole } from '@prisma/client';

export { UserRole };

export const ROLE_PERMISSIONS: Record<UserRole, string[]> = {
  CITIZEN: [
    'VIEW_OWN_PROFILE',
    'VIEW_OWN_APPOINTMENTS',
    'BOOK_OWN_APPOINTMENT',
    'CANCEL_OWN_APPOINTMENT',
    'VIEW_OWN_QUEUE_STATUS',
    'VIEW_OWN_REFERRALS',
    'VIEW_OWN_TIMELINE',
    'VIEW_OWN_FOLLOWUPS',
    'VIEW_OWN_NOTIFICATIONS',
    'VIEW_PUBLIC_FACILITIES',
  ],
  CHW: [
    'REGISTER_PATIENT',
    'VIEW_ASSIGNED_PATIENTS',
    'UPDATE_ASSIGNED_PATIENTS',
    'CREATE_TRIAGE',
    'CREATE_PRIMARY_REFERRAL',
    'VIEW_ASSIGNED_REFERRALS',
    'VIEW_ASSIGNED_FOLLOWUPS',
    'QUEUE_OFFLINE_SYNC',
    'VIEW_PUBLIC_FACILITIES',
  ],
  DOCTOR: [
    'VIEW_CLINICAL_WORKLIST',
    'VIEW_PATIENT_CLINICAL',
    'CREATE_ENCOUNTER',
    'MANAGE_FACILITY_QUEUE',
    'CALL_NEXT_PATIENT',
    'COMPLETE_CONSULTATION',
    'CREATE_SECONDARY_REFERRAL',
    'ACCEPT_REFERRAL',
    'REJECT_REFERRAL',
    'VIEW_FACILITY_REFERRALS',
  ],
  FACILITY_ADMIN: [
    'VIEW_FACILITY_OVERVIEW',
    'VIEW_FACILITY_PATIENTS',
    'VIEW_FACILITY_APPOINTMENTS',
    'MANAGE_FACILITY_QUEUE',
    'CREATE_WALKIN_TOKEN',
    'CALL_NEXT_PATIENT',
    'COMPLETE_CONSULTATION',
    'ACCEPT_REFERRAL',
    'REJECT_REFERRAL',
    'VIEW_FACILITY_REFERRALS',
    'VIEW_FACILITY_PRACTITIONERS',
    'VIEW_FACILITY_INVENTORY',
  ],
  DISTRICT_OFFICER: [
    'VIEW_DISTRICT_OVERVIEW',
    'VIEW_DISTRICT_FACILITIES',
    'VIEW_DISTRICT_MAP',
    'VIEW_DISTRICT_REFERRALS',
    'VIEW_DISTRICT_ANALYTICS',
    'VIEW_DATA_QUALITY_ISSUES',
    'RESOLVE_DATA_QUALITY_ISSUE',
  ],
  SUPER_ADMIN: [
    '*',
  ],
};

export function hasPermission(role: UserRole, permission: string): boolean {
  const perms = ROLE_PERMISSIONS[role] || [];
  return perms.includes('*') || perms.includes(permission);
}
